/* the file namespace on microvm, such as it is: a lookup order of
 * embed -> mount, same idea as a plan9 union directory. embed is a
 * fixed, build-time set of files (embedfs.h, generated by
 * scripts/gen_embedfs.lua) that always exists and never changes at
 * runtime -- core libs unlikely to ever need editing on the fly
 * (lib/thread.lua, lib/ninep.lua, ...). mount is a real namespace
 * reached over a driver (virtio-9p, once wired here -- see
 * docs/microvm-plan.md); it does not exist yet, so today embed is the
 * whole lookup and a miss is just a miss.
 *
 * when the mount half lands, it is a second lookup AFTER an embed
 * miss, in fs_open below -- not instead of embed, and not ahead of
 * it: the point of embedding these specific files is that they are
 * guaranteed present and fast regardless of what is or isn't mounted.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "embedfs.h"
#include "fs.h"

struct fs_handle {
	const char *path;
	const unsigned char *data;
	size_t len;
	size_t pos;
};

int
fs_init(void)
{
	return 0;	/* the embed half always exists */
}

static const struct embedfile *
find_embed(const char *path)
{
	for (size_t i = 0; i < embedfs_nfiles; i++)
		if (strcmp(embedfs_files[i].path, path) == 0)
			return &embedfs_files[i];
	return NULL;
}

void *
fs_open(const char *path, int write)
{
	if (write)
		return NULL;	/* embed is read-only; no mount to write to yet */

	const struct embedfile *e = find_embed(path);

	if (!e)
		return NULL;	/* would fall through to a mount lookup here */

	struct fs_handle *h = malloc(sizeof *h);

	if (!h)
		return NULL;
	h->path = e->path;
	h->data = e->data;
	h->len = e->len;
	h->pos = 0;
	return h;
}

long
fs_read(void *f, void *buf, long n)
{
	struct fs_handle *h = f;
	long avail = (long)(h->len - h->pos);

	if (n > avail)
		n = avail;
	if (n < 0)
		n = 0;
	memcpy(buf, h->data + h->pos, (size_t)n);
	h->pos += (size_t)n;
	return n;
}

long
fs_write(void *f, const void *buf, long n)
{
	(void)f;
	(void)buf;
	(void)n;
	return -1;	/* embed is read-only */
}

int
fs_seek(void *f, long pos, int whence)
{
	struct fs_handle *h = f;
	long base;

	switch (whence) {
	case 0:	/* SEEK_SET */
		base = 0;
		break;
	case 1:	/* SEEK_CUR */
		base = (long)h->pos;
		break;
	case 2:	/* SEEK_END */
		base = (long)h->len;
		break;
	default:
		return -1;
	}

	long np = base + pos;

	if (np < 0 || (size_t)np > h->len)
		return -1;
	h->pos = (size_t)np;
	return 0;
}

long
fs_tell(void *f)
{
	struct fs_handle *h = f;

	return (long)h->pos;
}

int
fs_flush(void *f)
{
	(void)f;
	return 0;
}

void
fs_close(void *f)
{
	free(f);
}

int
fs_readdir(void *f, struct fs_dirent *ent)
{
	(void)f;
	(void)ent;
	return -1;	/* the embed set is flat; nothing here is a directory */
}

int
fs_stat(void *f, struct fs_dirent *ent)
{
	struct fs_handle *h = f;
	const char *slash = strrchr(h->path, '/');
	const char *base = slash ? slash + 1 : h->path;

	memset(ent, 0, sizeof *ent);
	snprintf(ent->name, sizeof ent->name, "%s", base);
	ent->size = h->len;
	ent->isdir = 0;
	return 0;
}
