#ifndef HOSTED_EMBEDFS_H
#define HOSTED_EMBEDFS_H

#include <stddef.h>

/* generated by tools/gen_embedfs.lua from tools/embedtree.lua's list:
 * read-only, chosen at build time, never changing at runtime. fs.c
 * serves it as the root when --no-host-fs left no directory to serve.
 */
struct embedfile {
	const char *path;
	const unsigned char *data;
	size_t len;
};

extern const struct embedfile embedfs_files[];
extern const size_t embedfs_nfiles;

#endif
