#!/usr/bin/env lua
-- bdf2font.lua FONT.bdf OUT.h -- a bitmap font as C data.
--
--	lua tools/bdf2font.lua fonts/spleen-6x12.bdf src/font_spleen.h

-- Every glyph the font has, not a 256-entry slice of it: the codepoints
-- a bitmap font covers are a handful of contiguous runs, so the table
-- is those runs plus one bitmap array, and a lookup is a search over
-- the runs. A byte-indexed array cannot express U+2500 at all.

-- In lua because this build has no other language and the guest is
-- written in this one. tools/gen_embedfs.lua makes the same argument.

-- One byte per row, so a glyph must be at most 8 pixels wide. Rows are
-- read from the high byte of each BDF row and padded to the font box:
-- spleen's glyphs all fill it, and a font whose glyphs do not would
-- need the BBX offsets this ignores.

local src, out = arg[1], arg[2]

if not src or not out then
	io.stderr:write("usage: bdf2font.lua FONT.bdf OUT.h\n")
	os.exit(1)
end

-- ---- read ----

local function parse(path)
	local f = assert(io.open(path, "r"))
	local w, h
	local glyphs = {}
	local cp, reading, rows = nil, false, {}

	for line in f:lines() do
		local k, rest = line:match("^(%S+)%s*(.*)$")

		if k == "FONTBOUNDINGBOX" then
			local a, b = rest:match("^(%-?%d+)%s+(%-?%d+)")

			w, h = tonumber(a), tonumber(b)
		elseif k == "ENCODING" then
			cp = tonumber(rest:match("^(%-?%d+)"))
		elseif k == "BITMAP" then
			reading, rows = true, {}
		elseif k == "ENDCHAR" then
			reading = false
			if cp and cp >= 0 then
				glyphs[cp] = rows
			end
			cp = nil
		elseif reading and k then
			-- the high byte: a row is padded to whole bytes and
			-- nothing past the eighth pixel is ours to draw
			rows[#rows + 1] = tonumber(k:sub(1, 2), 16) or 0
		end
	end
	f:close()
	return w, h, glyphs
end

local w, h, glyphs = parse(src)

if not w or not h then
	io.stderr:write("bdf2font: no FONTBOUNDINGBOX in " .. src .. "\n")
	os.exit(1)
end
if w > 8 then
	io.stderr:write("bdf2font: width " .. w ..
	    " does not fit one byte per row\n")
	os.exit(1)
end

-- ---- the runs ----

local cps = {}

for cp in pairs(glyphs) do
	cps[#cps + 1] = cp
end
table.sort(cps)

if #cps == 0 then
	io.stderr:write("bdf2font: no glyphs in " .. src .. "\n")
	os.exit(1)
end

local ranges = {}
local first, prev = cps[1], cps[1]

for i = 2, #cps do
	local cp = cps[i]

	if cp ~= prev + 1 then
		ranges[#ranges + 1] = { first = first, last = prev }
		first = cp
	end
	prev = cp
end
ranges[#ranges + 1] = { first = first, last = prev }

-- where each run starts in the bitmap array, so a lookup is one add
local at = 0

for _, r in ipairs(ranges) do
	r.at = at
	at = at + (r.last - r.first + 1)
end

-- ---- write ----

local o = assert(io.open(out, "w"))

o:write(([[
/* GENERATED by tools/bdf2font.lua from fonts/%s -- do not edit. */
/* Spleen glyphs, (c) 2018-2024 Frederic Cambus, BSD 2-Clause. Terms */
/* in fonts/LICENSE; a copy of this file must keep this notice. */
/* One byte per row, top FONT_W bits used, FONT_H rows per glyph. */
/* Codepoints come in runs: font_ranges is searched, a glyph sits at */
/* `at` plus the distance into its run. */
#ifndef LUAOS_FONT_SPLEEN_H
#define LUAOS_FONT_SPLEEN_H
#include <stdint.h>
#define FONT_W %d
#define FONT_H %d
#define FONT_NGLYPH %d
#define FONT_NRANGE %d

struct font_range {
	uint16_t first;
	uint16_t last;
	uint16_t at;
};

static const struct font_range font_ranges[FONT_NRANGE] = {
]]):format(src:match("([^/]+)$") or src, w, h, #cps, #ranges))

for _, r in ipairs(ranges) do
	o:write(("\t{ 0x%04x, 0x%04x, %d },\n"):format(r.first, r.last, r.at))
end

o:write("};\n\nstatic const uint8_t font_glyphs[FONT_NGLYPH][FONT_H] = {\n")

-- unlabelled: font_ranges above says which codepoints these are, and a
-- comment per glyph is 548 of them for one fact already written down.
for _, r in ipairs(ranges) do
	for cp = r.first, r.last do
		local rows = glyphs[cp]
		local parts = {}

		for i = 1, h do
			parts[i] = ("0x%02x"):format(rows[i] or 0)
		end
		o:write("\t{" .. table.concat(parts, ",") .. "},\n")
	end
end

o:write("};\n\n#endif\n")
o:close()

io.stderr:write(("bdf2font: %d glyphs in %d runs, U+%04X..U+%04X\n")
    :format(#cps, #ranges, cps[1], cps[#cps]))
