#!/usr/bin/env lua5.4
-- gen_embedfs.lua OUTPUT.c GUESTPATH=HOSTFILE [GUESTPATH=HOSTFILE ...]
--
-- turns a handful of host files into one C source: a byte array per
-- file plus a {path, data, len} lookup table, for
-- src/platform/microvm/fs.c to serve as its whole file source (see
-- fs.c). there is no disk on microvm, so this is how a small,
-- deliberately-chosen set of lib/*.lua files gets to exist at all
-- before anything has mounted a namespace to hold the rest.
--
-- not the ld -r -b binary/objcopy trick: that ties symbol names to
-- objcopy's path-mangling scheme, which varies by binutils version. a
-- generated C array needs nothing beyond the C compiler already in
-- the build, and the generator is this project's own language.

local out_path = arg[1]
if not out_path or #arg < 2 then
	io.stderr:write("usage: gen_embedfs.lua OUTPUT.c GUESTPATH=HOSTFILE ...\n")
	os.exit(1)
end

local out = assert(io.open(out_path, "w"))

out:write("/* generated by scripts/gen_embedfs.lua -- do not edit */\n")
out:write('#include "embedfs.h"\n\n')

local entries = {}

for i = 2, #arg do
	local guest, host = arg[i]:match("^([^=]+)=(.+)$")
	if not guest then
		io.stderr:write("bad argument (want GUESTPATH=HOSTFILE): " ..
		    arg[i] .. "\n")
		os.exit(1)
	end

	local f = assert(io.open(host, "rb"))
	local data = f:read("a")
	f:close()

	local sym = "embedfs_" .. (i - 2)
	entries[#entries + 1] = { guest = guest, sym = sym, data = data }

	out:write(string.format("static const unsigned char %s[] = {", sym))
	for j = 1, #data do
		out:write(string.byte(data, j), ",")
	end
	out:write("};\n")
end

out:write("\nconst struct embedfile embedfs_files[] = {\n")
for _, e in ipairs(entries) do
	out:write(string.format('\t{ "%s", %s, sizeof %s },\n',
	    e.guest, e.sym, e.sym))
end
out:write("};\n")
out:write("const size_t embedfs_nfiles = " ..
    "sizeof embedfs_files / sizeof embedfs_files[0];\n")

out:close()
