#!/usr/bin/env lua5.4
-- version_h.lua IN OUT -- the revision as a C header.
--
-- Separate from version.lua so the string has exactly one author: this
-- only wraps what that produced, and cannot disagree with the copy in
-- an embedded file or on a filesystem image.

local inp = arg[1] or error("usage: version_h.lua IN OUT", 0)
local out = arg[2] or error("usage: version_h.lua IN OUT", 0)

local f = assert(io.open(inp, "r"))
local rev = f:read("l") or "unknown"

f:close()

local o = assert(io.open(out, "w"))

o:write("/* generated by tools/version_h.lua; do not edit */\n")
o:write("#ifndef LUAOS_REVISION_H\n#define LUAOS_REVISION_H\n")
o:write(("#define LUAOS_REV %q\n"):format(rev))
o:write("#endif\n")
o:close()
