#ifndef WASM_EMBEDFS_H
#define WASM_EMBEDFS_H

#include <stddef.h>

/* generated by scripts/gen_embedfs.lua from a fixed file list in
 * meson.build -- read-only, chosen at build time, never changes at
 * runtime. see fs.c for how this fits into the embed -> namespace
 * lookup order.
 */
struct embedfile {
	const char *path;
	const unsigned char *data;
	size_t len;
};

extern const struct embedfile embedfs_files[];
extern const size_t embedfs_nfiles;

#endif
