local sys = require("los.sys")
local thread = require("los.thread")
local tap = require("tap")
tap.plan(2)
local cons = sys.newport("zzz")
local consh = sys.sendright(cons)
local got
thread.spawn(function()
	local m = thread.recv(cons)
	print("# cons got op=" .. tostring(m.op) .. " right=" .. tostring(m.reply and m.reply.__right))
	print("# cons sent -> " .. tostring(sys.send(m.reply.__right, "line\n")))
end)
thread.spawn(function()
	got = thread.readline(consh)
	print("# readline -> " .. tostring(got))
end)
thread.run()
tap.ok(true, "ran")
tap.is(got, "line\n", "got the line")
tap.done()
